### ISSUE TITLE
Negative side lengths should be prohibited

### ISSUE THREAD

**Issue by WJPierro** [hoffmannmatheus/GradSSW567#1]
Negative side lengths should throw an InvalidTriangleException when passed to the Triangle constructor.

**Comment by hoffmannmatheus** [comment]
When constructing, it runs the function [hasValidSides](https://github.com/hoffmannmatheus/GradSSW567/blob/master/src/ssw567/assignment1/src/Triangle.java#L69). Did you find any combination of negative+positve or negative+negative sides that pass through? I tried a number of alternatives here but it always gives me the InvalidTriangleException.

**Comment by WJPierro** [comment]
I wrote this up just to test the issue tracking.  I just looked at the tests in hasValidSides and yes it does like any negative input will raise the exception.

**Comment by hoffmannmatheus** [comment]
All right :)

**Comment by WJPierro** [comment]
Closing this issue.
